# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\User:
            algorithm: auto
    firewalls:
        main:
           form_login:
                login_path: login
                check_path: login        
